### ISSUE TITLE
Service doesn't  show up activity to entitity on home assistant 2021.12.1 core

### ISSUE THREAD

**Issue by rodrigogbs** [sleevezipper/hass-workstation-service#147]
After updating HA to core 2021.12.1 the service shows up the entity on HA, but not the activity, the entitiy status is constantly unavailable.

MQTT logs:

-------------------------------------------------------------------------------------------------------------------
[services.d] done.
[15:32:10] INFO: Starting NGINX for authentication handling...
[15:32:10] INFO: Starting mosquitto MQTT broker...
1639420330: mosquitto version 1.6.12 starting
1639420330: |-- *** auth-plug: startup
1639420330: Config loaded from /etc/mosquitto/mosquitto.conf.
1639420330: Loading plugin: /usr/share/mosquitto/auth-plug.so
1639420330:  ├── Username/password checking enabled.
1639420330:  ├── TLS-PSK checking enabled.
1639420330:  └── Extended authentication not enabled.
1639420330: Opening ipv4 listen socket on port 1883.
1639420330: Opening ipv6 listen socket on port 1883.
1639420330: Opening websockets listen socket on port 1884.
1639420331: Opening ipv4 listen socket on port 8883.
1639420331: Opening ipv6 listen socket on port 8883.
1639420331: Opening websockets listen socket on port 8884.
1639420331: Warning: Mosquitto should not be run as root/administrator.
1639420331: mosquitto version 1.6.12 running
1639420331: New connection from 127.0.0.1 on port 1883.
1639420331: Socket error on client <unknown>, disconnecting.
1639420331: New connection from 172.30.33.5 on port 1883.
1639420331: New client connected from 172.30.33.5 as mqttjs_1ae2cf60 (p2, c1, k60, u'mqttuser').
[15:32:11] INFO: Successfully send discovery information to Home Assistant.
[15:32:12] INFO: Successfully send service information to the Supervisor.
1639420331: New connection from 192.168.68.138 on port 1883.
1639420331: New client connected from 192.168.68.138 as 3a7e5e22571c489887c43674b9550815 (p2, c1, k30, u'mqttuser').
1639420333: New connection from 172.30.32.1 on port 1883.
1639420333: New client connected from 172.30.32.1 as 3zgb631365abeFo77PESmN (p2, c1, k60, u'mqttuser').
1639420386: New connection from 172.30.32.2 on port 1883.
1639420386: Socket error on client <unknown>, disconnecting.
1639420408: Client 3a7e5e22571c489887c43674b9550815 disconnected.
1639420408: New connection from 192.168.68.138 on port 1883.
1639420408: New client connected from 192.168.68.138 as c5a4fc5f9646488ca51b9d699e35c221 (p2, c1, k30, u'mqttuser').
1639420413: Client c5a4fc5f9646488ca51b9d699e35c221 disconnected.
1639420417: New connection from 192.168.68.138 on port 1883.
1639420417: New client connected from 192.168.68.138 as f017a9500b48416bbd20e662f6e515bf (p2, c1, k30, u'mqttuser').
1639420490: Client f017a9500b48416bbd20e662f6e515bf disconnected.
1639420490: New connection from 192.168.68.138 on port 8883.
1639420490: New client connected from 192.168.68.138 as 281ca7d91fc04117904f33e1d65b5f1f (p2, c1, k30, u'mqttuser').
1639420506: New connection from 172.30.32.2 on port 1883.
1639420506: Socket error on client <unknown>, disconnecting.
1639420506: Client 281ca7d91fc04117904f33e1d65b5f1f disconnected.
1639420506: New connection from 192.168.68.138 on port 8883.
1639420506: New client connected from 192.168.68.138 as dbb3fc63a2434f589f4f84ceef3ecc5b (p2, c1, k30, u'mqttuser').
1639420511: Client dbb3fc63a2434f589f4f84ceef3ecc5b disconnected.
1639420515: New connection from 192.168.68.138 on port 8883.
1639420516: New client connected from 192.168.68.138 as 93bb1cffa29549298e813dbe8743b5d4 (p2, c1, k30, u'mqttuser').
1639420626: New connection from 172.30.32.2 on port 1883.
1639420626: Socket error on client <unknown>, disconnecting.
1639420746: New connection from 172.30.32.2 on port 1883.
1639420746: Socket error on client <unknown>, disconnecting.
1639420866: New connection from 172.30.32.2 on port 1883.
1639420866: Socket error on client <unknown>, disconnecting.
1639420986: New connection from 172.30.32.2 on port 1883.
1639420986: Socket error on client <unknown>, disconnecting.
1639421086: Socket error on client 3zgb631365abeFo77PESmN, disconnecting.
1639421106: New connection from 172.30.32.2 on port 1883.
1639421106: Socket error on client <unknown>, disconnecting.
1639421109: New connection from 172.30.32.1 on port 1883.
1639421109: New client connected from 172.30.32.1 as 136tMuQnOYiGfMKn5MMWv7 (p2, c1, k60, u'mqttuser').
1639421226: New connection from 172.30.32.2 on port 1883.
1639421226: Socket error on client <unknown>, disconnecting.
1639421346: New connection from 172.30.32.2 on port 1883.
1639421346: Socket error on client <unknown>, disconnecting.
1639421466: New connection from 172.30.32.2 on port 1883.
1639421466: Socket error on client <unknown>, disconnecting.
1639421586: New connection from 172.30.32.2 on port 1883.
1639421586: Socket error on client <unknown>, disconnecting.
1639421706: New connection from 172.30.32.2 on port 1883.
1639421706: Socket error on client <unknown>, disconnecting.
1639421826: New connection from 172.30.32.2 on port 1883.
1639421826: Socket error on client <unknown>, disconnecting.
1639421946: New connection from 172.30.32.2 on port 1883.
1639421946: Socket error on client <unknown>, disconnecting.
1639421974: Client 93bb1cffa29549298e813dbe8743b5d4 disconnected.
1639421974: Client connection from 192.168.68.138 failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.
1639421978: New connection from 192.168.68.138 on port 1883.
1639421978: New client connected from 192.168.68.138 as 1cf81c24046d42ea9ee20dfcbcd4d7a3 (p2, c1, k30, u'mqttuser').
1639422066: New connection from 172.30.32.2 on port 1883.
1639422066: Socket error on client <unknown>, disconnecting.
1639422098: Socket error on client 136tMuQnOYiGfMKn5MMWv7, disconnecting.
1639422131: Saving in-memory database to /data/mosquitto.db.
1639422149: New connection from 172.30.32.1 on port 1883.
1639422149: New client connected from 172.30.32.1 as 7dSKq13N5mcIHCOxKN0QoC (p2, c1, k60, u'mqttuser').
1639422186: New connection from 172.30.32.2 on port 1883.
1639422186: Socket error on client <unknown>, disconnecting.
1639422306: New connection from 172.30.32.2 on port 1883.
1639422306: Socket error on client <unknown>, disconnecting.
1639422426: New connection from 172.30.32.2 on port 1883.
1639422426: Socket error on client <unknown>, disconnecting.
1639422522: Socket error on client 7dSKq13N5mcIHCOxKN0QoC, disconnecting.
1639422543: New connection from 172.30.32.1 on port 1883.
1639422543: New client connected from 172.30.32.1 as 3R6niKs5VfWilonXYwy3SC (p2, c1, k60, u'mqttuser').
1639422546: New connection from 172.30.32.2 on port 1883.
1639422546: Socket error on client <unknown>, disconnecting.
1639422666: New connection from 172.30.32.2 on port 1883.
1639422666: Socket error on client <unknown>, disconnecting.
1639422786: New connection from 172.30.32.2 on port 1883.
1639422786: Socket error on client <unknown>, disconnecting.
1639422906: New connection from 172.30.32.2 on port 1883.
-------------------------------------------------------------------------------------------------------------------

The PC that is providing the sensor is 192.168.68.138.

HA log:

-------------------------------------------------------------------------------------------------------------------
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 4:09:18 PM (375 occurrences)
Last logged: 4:33:14 PM

Exception in message_received when handling msg on 'homeassistant/sensor/LT09264/Notebook_Neogrid_Atividade/state': '2021-12-13T16:33:03' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-13 16:33:03', which is missing timezone information
Exception in availability_message_received when handling msg on 'homeassistant/sensor/LT09264/availability': 'online' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 385, in availability_message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-13 16:33:03', which is missing timezone information
Exception in message_received when handling msg on 'homeassistant/sensor/LT09264/Notebook_Neogrid_Atividade/state': '2021-12-13T16:33:08' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-13 16:33:08', which is missing timezone information
Exception in message_received when handling msg on 'homeassistant/sensor/LT09264/Notebook_Neogrid_Atividade/state': '2021-12-13T16:33:13' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-13 16:33:13', which is missing timezone information
Exception in availability_message_received when handling msg on 'homeassistant/sensor/LT09264/availability': 'online' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 385, in availability_message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-13 16:33:13', which is missing timezone information
-------------------------------------------------------------------------------------------------------------------

**Comment by sleevezipper** [comment]
Hi! This should be fixed in the latest version. Have you updated yet?

**Comment by rodrigogbs** [comment]
@sleevezipper yes, I have just updated and restarted HA and also the PC, but the problem remains the same.

------------------------------------------------------------------------------------------------------------------------------------------
Core
Version
core-2021.12.2

Supervisor
Version
supervisor-2021.12.2

Host
Operating System
Home Assistant OS 7.0
------------------------------------------------------------------------------------------------------------------------------------------

HA logs:

Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 7:26:12 PM (25 occurrences)
Last logged: 7:27:35 PM

Exception in message_received when handling msg on 'homeassistant/sensor/LT09264/Notebook_Neogrid_Atividade/state': '2021-12-15T19:27:23' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-15 19:27:23', which is missing timezone information
Exception in availability_message_received when handling msg on 'homeassistant/sensor/LT09264/availability': 'online' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 385, in availability_message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-15 19:27:23', which is missing timezone information
Exception in message_received when handling msg on 'homeassistant/sensor/LT09264/Notebook_Neogrid_Atividade/state': '2021-12-15T19:27:28' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-15 19:27:28', which is missing timezone information
Exception in message_received when handling msg on 'homeassistant/sensor/LT09264/Notebook_Neogrid_Atividade/state': '2021-12-15T19:27:34' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-15 19:27:34', which is missing timezone information
Exception in availability_message_received when handling msg on 'homeassistant/sensor/LT09264/availability': 'online' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 385, in availability_message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.notebook_neogrid_atividade provides state '2021-12-15 19:27:34', which is missing timezone information

**Comment by rodrigogbs** [comment]
@sleevezipper after updating the hass-workstation-service standalone to the latest version the issue was resolved and the sensor is now active again! Thanks!

**Comment by sleevezipper** [comment]
Awesome! Thanks for letting me know.
